# -*- mode: shell-script -*-
# Executes commands at login pre-zshrc.

export EDITOR='emacsclient'
export VISUAL='emacsclient'
export PAGER='most'
export BROWSER=google-chrome

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin
  /usr/local/bin
  $HOME/.rvm/bin
  $path
)

alias xfce4-terminal='xfce4-terminal --disable-server'
