# -*- mode: shell-script -*-

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz promptinit; promptinit
PURE_GIT_PULL=0
PURE_CMD_MAX_EXEC_TIME=60
prompt pure

bindkey -N my-keymap emacs
bindkey -A my-keymap main
bindkey -r "^L"  # disable obsessive screen clearing
bindkey "^U" backward-kill-line

export EDITOR=emacsclient
export PAGER=most
export BROWSER=google-chrome

export BACKGROUNDS=~/keep/backgrounds

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls -lh --color --group-directories-first'
alias wget_head='wget -qSO /dev/null'
alias mutt='mutt -F ~/.mutt/profiles/zoion/main'
alias mutt_birchbox='mutt -F ~/.mutt/profiles/birchbox/main'
alias feh="feh --auto-zoom --action1 'fbsetbg %f'"
alias emacs=emacsclient

function poll_mail {
    local interval=${1:=120}
    while true; do
        $HOME/.mutt/bin/get_mail.sh
        echo "sleeping for $interval seconds..."
        sleep $interval
    done
}

function rename_to_sha1 {
    for f in *(.); do
        ext=$(echo $f | perl -F'\.' -ae 'print $F[-1]')
        sha1=$(sha1sum $f | perl -ae 'print $F[0]')
        mv -v "$f" "${sha1}.${ext}"
    done
}
